import * as Parser from '../parser/jsonParser';
import * as SchemaService from './jsonSchemaService';
import { JSONWorkerContribution } from '../jsonContributions';
import { PromiseConstructor, Thenable, ClientCapabilities, TextDocument, CompletionItem, CompletionList, Position } from '../jsonLanguageTypes';
export declare class JSONCompletion {
    private schemaService;
    private contributions;
    private promiseConstructor;
    private clientCapabilities;
    private supportsMarkdown;
    private supportsCommitCharacters;
    constructor(schemaService: SchemaService.IJSONSchemaService, contributions?: JSONWorkerContribution[], promiseConstructor?: PromiseConstructor, clientCapabilities?: ClientCapabilities);
    doResolve(item: CompletionItem): Thenable<CompletionItem>;
    doComplete(document: TextDocument, position: Position, doc: Parser.JSONDocument): Thenable<CompletionList>;
    private getPropertyCompletions;
    private getSchemaLessPropertyCompletions;
    private getSchemaLessValueCompletions;
    private getValueCompletions;
    private getContributedValueCompletions;
    private addSchemaValueCompletions;
    private addDefaultValueCompletions;
    private addEnumValueCompletions;
    private collectTypes;
    private addFillerValueCompletions;
    private addBooleanValueCompletion;
    private addNullValueCompletion;
    private addDollarSchemaCompletions;
    private getLabelForValue;
    private getFilterTextForValue;
    private getFilterTextForSnippetValue;
    private getLabelForSnippetValue;
    private getInsertTextForPlainText;
    private getInsertTextForValue;
    private getInsertTextForSnippetValue;
    private getInsertTextForGuessedValue;
    private getSuggestionKind;
    private getLabelTextForMatchingNode;
    private getInsertTextForMatchingNode;
    private getInsertTextForProperty;
    private getCurrentWord;
    private evaluateSeparatorAfter;
    private findItemAtOffset;
    private isInComment;
    private fromMarkup;
    private doesSupportMarkdown;
    private doesSupportsCommitCharacters;
}
